import { supabase } from './supabase';

/**
 * Runs the automatic monthly rent and due generation logic.
 * Should be called once upon layout load/auth load.
 */
export async function runAutoMonthlyRentGeneration() {
  try {
    // 1. Fetch settings from app_settings
    const { data: settings, error: settingsErr } = await supabase
      .from('app_settings')
      .select('*')
      .maybeSingle();

    if (settingsErr || !settings) {
      console.log('Auto Rent Service: Settings not found or error loading settings.');
      return;
    }

    // Check if auto rent generation is enabled
    if (!settings.auto_bill_generate) {
      console.log('Auto Rent Service: Auto rent generation is disabled in settings.');
      return;
    }

    const now = new Date();
    const currentMonth = now.getMonth() + 1; // 1-12
    const currentYear = now.getFullYear();

    console.log(`Auto Rent Service: Checking auto rent generation for ${currentMonth}/${currentYear}...`);

    // 2. Fetch all occupied flats
    const { data: flats, error: flatsErr } = await supabase
      .from('flats')
      .select('*')
      .eq('status', 'occupied');

    if (flatsErr || !flats || flats.length === 0) {
      console.log('Auto Rent Service: No occupied flats found.');
      return;
    }

    // 3. Process each occupied flat
    for (const flat of flats) {
      // Check if a rent collection record already exists for this flat, month, and year
      const { data: existingCol, error: colCheckErr } = await supabase
        .from('rent_collections')
        .select('id')
        .eq('flat_id', flat.id)
        .eq('month', currentMonth)
        .eq('year', currentYear)
        .maybeSingle();

      if (colCheckErr) {
        console.error(`Auto Rent Service: Error checking collection for flat ${flat.flat_number}:`, colCheckErr);
        continue;
      }

      let electricBill = 0;

      // Handle meter reading generation if configured
      if (settings.auto_carry_meter_reading || settings.auto_meter_calculation) {
        // Check if meter reading exists for current month/year
        const { data: existingMeter, error: meterCheckErr } = await supabase
          .from('meter_readings')
          .select('*')
          .eq('flat_id', flat.id)
          .eq('month', currentMonth)
          .eq('year', currentYear)
          .maybeSingle();

        if (!meterCheckErr && !existingMeter) {
          // Fetch previous month's meter reading to carry forward
          const { data: lastMeter } = await supabase
            .from('meter_readings')
            .select('*')
            .eq('flat_id', flat.id)
            .order('year', { ascending: false })
            .order('month', { ascending: false })
            .limit(1)
            .maybeSingle();

          const prevReading = lastMeter ? Number(lastMeter.current_reading) : 0;
          const perUnit = Number(settings.electricity_per_unit) || (lastMeter ? Number(lastMeter.per_unit_price) : 7);

          // Auto carry meter reading: insert initial entry with current = previous
          const { data: newMeter, error: insertMeterErr } = await supabase
            .from('meter_readings')
            .insert({
              flat_id: flat.id,
              month: currentMonth,
              year: currentYear,
              previous_reading: prevReading,
              current_reading: prevReading,
              per_unit_price: perUnit,
            })
            .select()
            .maybeSingle();

          if (insertMeterErr) {
            console.error(`Auto Rent Service: Error creating meter reading for flat ${flat.flat_number}:`, insertMeterErr);
          } else if (newMeter) {
            electricBill = Number(newMeter.total_bill) || 0;
          }
        } else if (existingMeter) {
          electricBill = Number(existingMeter.total_bill) || 0;
        }
      }

      // If rent collection record does not exist, auto-create it
      if (!existingCol) {
        const monthlyRent = Number(flat.monthly_rent) || 0;
        const waterBill = Number(flat.water_bill) || 0;
        const serviceCharge = Number(flat.service_charge) || 0;
        const totalPayable = monthlyRent + waterBill + serviceCharge + electricBill;

        const { error: insertColErr } = await supabase
          .from('rent_collections')
          .insert({
            flat_id: flat.id,
            month: currentMonth,
            year: currentYear,
            monthly_rent: monthlyRent,
            electric_bill: electricBill,
            water_bill: waterBill,
            service_charge: serviceCharge,
            total_payable: totalPayable,
            amount_paid: 0,
            payment_status: 'pending',
            notes: 'Automatically generated by system',
          });

        if (insertColErr) {
          console.error(`Auto Rent Service: Error inserting collection for flat ${flat.flat_number}:`, insertColErr);
        } else {
          console.log(`Auto Rent Service: Generated rent collection for flat ${flat.flat_number}`);
        }
      }
    }
  } catch (err) {
    console.error('Auto Rent Service: Unhandled error during generation:', err);
  }
}
